spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/currency_trends_monitor_prod
    username: ctms_prod_user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false