-- Countries
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (1, 'AD', 'Andorra');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (2, 'AE', 'United Arab Emirates');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (3, 'AF', 'Afghanistan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (4, 'AG', 'Antigua & Barbuda');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (5, 'AI', 'Anguilla');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (6, 'AL', 'Albania');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (7, 'AM', 'Armenia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (8, 'AO', 'Angola');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (9, 'AQ', 'Antarctica');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (10, 'AR', 'Argentina');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (11, 'AS', 'American Samoa');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (12, 'AT', 'Austria');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (13, 'AU', 'Australia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (14, 'AW', 'Aruba');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (15, 'AX', 'Åland Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (16, 'AZ', 'Azerbaijan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (17, 'BA', 'Bosnia & Herzegovina');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (18, 'BB', 'Barbados');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (19, 'BD', 'Bangladesh');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (20, 'BE', 'Belgium');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (21, 'BF', 'Burkina Faso');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (22, 'BG', 'Bulgaria');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (23, 'BH', 'Bahrain');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (24, 'BI', 'Burundi');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (25, 'BJ', 'Benin');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (26, 'BL', 'St. Barthélemy');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (27, 'BM', 'Bermuda');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (28, 'BN', 'Brunei');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (29, 'BO', 'Bolivia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (30, 'BQ', 'Caribbean Netherlands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (31, 'BR', 'Brazil');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (32, 'BS', 'Bahamas');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (33, 'BT', 'Bhutan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (34, 'BV', 'Bouvet Island');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (35, 'BW', 'Botswana');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (36, 'BY', 'Belarus');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (37, 'BZ', 'Belize');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (38, 'CA', 'Canada');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (39, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (40, 'CD', 'Congo - Kinshasa');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (41, 'CF', 'Central African Republic');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (42, 'CG', 'Congo - Brazzaville');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (43, 'CH', 'Switzerland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (44, 'CI', 'Côte d’Ivoire');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (45, 'CK', 'Cook Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (46, 'CL', 'Chile');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (47, 'CM', 'Cameroon');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (48, 'CN', 'China');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (49, 'CO', 'Colombia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (50, 'CR', 'Costa Rica');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (51, 'CU', 'Cuba');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (52, 'CV', 'Cape Verde');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (53, 'CW', 'Curaçao');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (54, 'CX', 'Christmas Island');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (55, 'CY', 'Cyprus');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (56, 'CZ', 'Czechia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (57, 'DE', 'Germany');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (58, 'DJ', 'Djibouti');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (59, 'DK', 'Denmark');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (60, 'DM', 'Dominica');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (61, 'DO', 'Dominican Republic');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (62, 'DZ', 'Algeria');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (63, 'EC', 'Ecuador');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (64, 'EE', 'Estonia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (65, 'EG', 'Egypt');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (66, 'EH', 'Western Sahara');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (67, 'ER', 'Eritrea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (68, 'ES', 'Spain');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (69, 'ET', 'Ethiopia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (70, 'FI', 'Finland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (71, 'FJ', 'Fiji');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (72, 'FK', 'Falkland Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (73, 'FM', 'Micronesia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (74, 'FO', 'Faroe Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (75, 'FR', 'France');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (76, 'GA', 'Gabon');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (77, 'GB', 'United Kingdom');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (78, 'GD', 'Grenada');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (79, 'GE', 'Georgia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (80, 'GF', 'French Guiana');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (81, 'GG', 'Guernsey');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (82, 'GH', 'Ghana');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (83, 'GI', 'Gibraltar');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (84, 'GL', 'Greenland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (85, 'GM', 'Gambia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (86, 'GN', 'Guinea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (87, 'GP', 'Guadeloupe');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (88, 'GQ', 'Equatorial Guinea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (89, 'GR', 'Greece');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (90, 'GS', 'South Georgia & South Sandwich Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (91, 'GT', 'Guatemala');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (92, 'GU', 'Guam');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (93, 'GW', 'Guinea-Bissau');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (94, 'GY', 'Guyana');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (95, 'HK', 'Hong Kong SAR China');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (96, 'HM', 'Heard & McDonald Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (97, 'HN', 'Honduras');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (98, 'HR', 'Croatia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (99, 'HT', 'Haiti');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (100, 'HU', 'Hungary');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (101, 'ID', 'Indonesia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (102, 'IE', 'Ireland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (103, 'IL', 'Israel');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (104, 'IM', 'Isle of Man');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (105, 'IN', 'India');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (106, 'IO', 'British Indian Ocean Territory');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (107, 'IQ', 'Iraq');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (108, 'IR', 'Iran');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (109, 'IS', 'Iceland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (110, 'IT', 'Italy');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (111, 'JE', 'Jersey');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (112, 'JM', 'Jamaica');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (113, 'JO', 'Jordan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (114, 'JP', 'Japan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (115, 'KE', 'Kenya');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (116, 'KG', 'Kyrgyzstan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (117, 'KH', 'Cambodia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (118, 'KI', 'Kiribati');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (119, 'KM', 'Comoros');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (120, 'KN', 'St. Kitts & Nevis');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (121, 'KP', 'North Korea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (122, 'KR', 'South Korea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (123, 'KW', 'Kuwait');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (124, 'KY', 'Cayman Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (125, 'KZ', 'Kazakhstan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (126, 'LA', 'Laos');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (127, 'LB', 'Lebanon');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (128, 'LC', 'St. Lucia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (129, 'LI', 'Liechtenstein');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (130, 'LK', 'Sri Lanka');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (131, 'LR', 'Liberia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (132, 'LS', 'Lesotho');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (133, 'LT', 'Lithuania');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (134, 'LU', 'Luxembourg');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (135, 'LV', 'Latvia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (136, 'LY', 'Libya');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (137, 'MA', 'Morocco');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (138, 'MC', 'Monaco');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (139, 'MD', 'Moldova');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (140, 'ME', 'Montenegro');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (141, 'MF', 'St. Martin');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (142, 'MG', 'Madagascar');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (143, 'MH', 'Marshall Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (144, 'MK', 'Macedonia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (145, 'ML', 'Mali');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (146, 'MM', 'Myanmar (Burma)');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (147, 'MN', 'Mongolia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (148, 'MO', 'Macau SAR China');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (149, 'MP', 'Northern Mariana Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (150, 'MQ', 'Martinique');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (151, 'MR', 'Mauritania');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (152, 'MS', 'Montserrat');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (153, 'MT', 'Malta');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (154, 'MU', 'Mauritius');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (155, 'MV', 'Maldives');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (156, 'MW', 'Malawi');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (157, 'MX', 'Mexico');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (158, 'MY', 'Malaysia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (159, 'MZ', 'Mozambique');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (160, 'NA', 'Namibia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (161, 'NC', 'New Caledonia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (162, 'NE', 'Niger');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (163, 'NF', 'Norfolk Island');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (164, 'NG', 'Nigeria');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (165, 'NI', 'Nicaragua');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (166, 'NL', 'Netherlands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (167, 'NO', 'Norway');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (168, 'NP', 'Nepal');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (169, 'NR', 'Nauru');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (170, 'NU', 'Niue');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (171, 'NZ', 'New Zealand');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (172, 'OM', 'Oman');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (173, 'PA', 'Panama');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (174, 'PE', 'Peru');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (175, 'PF', 'French Polynesia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (176, 'PG', 'Papua New Guinea');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (177, 'PH', 'Philippines');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (178, 'PK', 'Pakistan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (179, 'PL', 'Poland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (180, 'PM', 'St. Pierre & Miquelon');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (181, 'PN', 'Pitcairn Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (182, 'PR', 'Puerto Rico');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (183, 'PS', 'Palestinian Territories');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (184, 'PT', 'Portugal');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (185, 'PW', 'Palau');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (186, 'PY', 'Paraguay');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (187, 'QA', 'Qatar');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (188, 'RE', 'Réunion');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (189, 'RO', 'Romania');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (190, 'RS', 'Serbia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (191, 'RU', 'Russia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (192, 'RW', 'Rwanda');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (193, 'SA', 'Saudi Arabia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (194, 'SB', 'Solomon Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (195, 'SC', 'Seychelles');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (196, 'SD', 'Sudan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (197, 'SE', 'Sweden');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (198, 'SG', 'Singapore');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (199, 'SH', 'St. Helena');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (200, 'SI', 'Slovenia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (201, 'SJ', 'Svalbard & Jan Mayen');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (202, 'SK', 'Slovakia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (203, 'SL', 'Sierra Leone');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (204, 'SM', 'San Marino');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (205, 'SN', 'Senegal');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (206, 'SO', 'Somalia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (207, 'SR', 'Suriname');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (208, 'SS', 'South Sudan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (209, 'ST', 'São Tomé & Príncipe');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (210, 'SV', 'El Salvador');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (211, 'SX', 'Sint Maarten');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (212, 'SY', 'Syria');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (213, 'SZ', 'Swaziland');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (214, 'TC', 'Turks & Caicos Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (215, 'TD', 'Chad');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (216, 'TF', 'French Southern Territories');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (217, 'TG', 'Togo');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (218, 'TH', 'Thailand');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (219, 'TJ', 'Tajikistan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (220, 'TK', 'Tokelau');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (221, 'TL', 'Timor-Leste');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (222, 'TM', 'Turkmenistan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (223, 'TN', 'Tunisia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (224, 'TO', 'Tonga');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (225, 'TR', 'Turkey');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (226, 'TT', 'Trinidad & Tobago');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (227, 'TV', 'Tuvalu');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (228, 'TW', 'Taiwan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (229, 'TZ', 'Tanzania');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (230, 'UA', 'Ukraine');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (231, 'UG', 'Uganda');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (232, 'UM', 'U.S. Outlying Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (233, 'US', 'United States');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (234, 'UY', 'Uruguay');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (235, 'UZ', 'Uzbekistan');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (236, 'VA', 'Vatican City');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (237, 'VC', 'St. Vincent & Grenadines');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (238, 'VE', 'Venezuela');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (239, 'VG', 'British Virgin Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (240, 'VI', 'U.S. Virgin Islands');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (241, 'VN', 'Vietnam');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (242, 'VU', 'Vanuatu');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (243, 'WF', 'Wallis & Futuna');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (244, 'WS', 'Samoa');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (245, 'YE', 'Yemen');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (246, 'YT', 'Mayotte');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (247, 'ZA', 'South Africa');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (248, 'ZM', 'Zambia');
INSERT INTO country (`id`, `iso_2_code`, `name`) VALUES (249, 'ZW', 'Zimbabwe');

-- Currencies
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (1, 'ADP', 'Andorran Peseta');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (2, 'AED', 'United Arab Emirates Dirham');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (3, 'AFA', 'Afghan Afghani (1927–2002)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (4, 'AFN', 'Afghan Afghani');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (5, 'ALL', 'Albanian Lek');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (6, 'AMD', 'Armenian Dram');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (7, 'ANG', 'Netherlands Antillean Guilder');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (8, 'AOA', 'Angolan Kwanza');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (9, 'ARS', 'Argentine Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (10, 'ATS', 'Austrian Schilling');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (11, 'AUD', 'Australian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (12, 'AWG', 'Aruban Florin');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (13, 'AYM', 'AYM');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (14, 'AZM', 'Azerbaijani Manat (1993–2006)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (15, 'AZN', 'Azerbaijani Manat');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (16, 'BAM', 'Bosnia-Herzegovina Convertible Mark');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (17, 'BBD', 'Barbadian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (18, 'BDT', 'Bangladeshi Taka');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (19, 'BEF', 'Belgian Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (20, 'BGL', 'Bulgarian Hard Lev');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (21, 'BGN', 'Bulgarian Lev');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (22, 'BHD', 'Bahraini Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (23, 'BIF', 'Burundian Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (24, 'BMD', 'Bermudan Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (25, 'BND', 'Brunei Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (26, 'BOB', 'Bolivian Boliviano');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (27, 'BOV', 'Bolivian Mvdol');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (28, 'BRL', 'Brazilian Real');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (29, 'BSD', 'Bahamian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (30, 'BTN', 'Bhutanese Ngultrum');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (31, 'BWP', 'Botswanan Pula');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (32, 'BYB', 'Belarusian Ruble (1994–1999)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (33, 'BYN', 'Belarusian Ruble');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (34, 'BYR', 'Belarusian Ruble (2000–2016)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (35, 'BZD', 'Belize Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (36, 'CAD', 'Canadian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (37, 'CDF', 'Congolese Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (38, 'CHE', 'WIR Euro');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (39, 'CHF', 'Swiss Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (40, 'CHW', 'WIR Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (41, 'CLF', 'Chilean Unit of Account (UF)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (42, 'CLP', 'Chilean Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (43, 'CNY', 'Chinese Yuan');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (44, 'COP', 'Colombian Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (45, 'COU', 'Colombian Real Value Unit');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (46, 'CRC', 'Costa Rican Colón');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (47, 'CSD', 'Serbian Dinar (2002–2006)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (48, 'CUC', 'Cuban Convertible Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (49, 'CUP', 'Cuban Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (50, 'CVE', 'Cape Verdean Escudo');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (51, 'CYP', 'Cypriot Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (52, 'CZK', 'Czech Koruna');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (53, 'DEM', 'German Mark');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (54, 'DJF', 'Djiboutian Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (55, 'DKK', 'Danish Krone');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (56, 'DOP', 'Dominican Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (57, 'DZD', 'Algerian Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (58, 'EEK', 'Estonian Kroon');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (59, 'EGP', 'Egyptian Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (60, 'ERN', 'Eritrean Nakfa');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (61, 'ESP', 'Spanish Peseta');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (62, 'ETB', 'Ethiopian Birr');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (63, 'EUR', 'Euro');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (64, 'FIM', 'Finnish Markka');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (65, 'FJD', 'Fijian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (66, 'FKP', 'Falkland Islands Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (67, 'FRF', 'French Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (68, 'GBP', 'British Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (69, 'GEL', 'Georgian Lari');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (70, 'GHC', 'Ghanaian Cedi (1979–2007)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (71, 'GHS', 'Ghanaian Cedi');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (72, 'GIP', 'Gibraltar Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (73, 'GMD', 'Gambian Dalasi');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (74, 'GNF', 'Guinean Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (75, 'GRD', 'Greek Drachma');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (76, 'GTQ', 'Guatemalan Quetzal');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (77, 'GWP', 'Guinea-Bissau Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (78, 'GYD', 'Guyanaese Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (79, 'HKD', 'Hong Kong Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (80, 'HNL', 'Honduran Lempira');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (81, 'HRK', 'Croatian Kuna');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (82, 'HTG', 'Haitian Gourde');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (83, 'HUF', 'Hungarian Forint');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (84, 'IDR', 'Indonesian Rupiah');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (85, 'IEP', 'Irish Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (86, 'ILS', 'Israeli New Shekel');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (87, 'INR', 'Indian Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (88, 'IQD', 'Iraqi Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (89, 'IRR', 'Iranian Rial');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (90, 'ISK', 'Icelandic Króna');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (91, 'ITL', 'Italian Lira');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (92, 'JMD', 'Jamaican Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (93, 'JOD', 'Jordanian Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (94, 'JPY', 'Japanese Yen');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (95, 'KES', 'Kenyan Shilling');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (96, 'KGS', 'Kyrgystani Som');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (97, 'KHR', 'Cambodian Riel');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (98, 'KMF', 'Comorian Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (99, 'KPW', 'North Korean Won');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (100, 'KRW', 'South Korean Won');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (101, 'KWD', 'Kuwaiti Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (102, 'KYD', 'Cayman Islands Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (103, 'KZT', 'Kazakhstani Tenge');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (104, 'LAK', 'Laotian Kip');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (105, 'LBP', 'Lebanese Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (106, 'LKR', 'Sri Lankan Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (107, 'LRD', 'Liberian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (108, 'LSL', 'Lesotho Loti');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (109, 'LTL', 'Lithuanian Litas');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (110, 'LUF', 'Luxembourgian Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (111, 'LVL', 'Latvian Lats');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (112, 'LYD', 'Libyan Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (113, 'MAD', 'Moroccan Dirham');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (114, 'MDL', 'Moldovan Leu');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (115, 'MGA', 'Malagasy Ariary');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (116, 'MGF', 'Malagasy Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (117, 'MKD', 'Macedonian Denar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (118, 'MMK', 'Myanmar Kyat');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (119, 'MNT', 'Mongolian Tugrik');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (120, 'MOP', 'Macanese Pataca');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (121, 'MRO', 'Mauritanian Ouguiya (1973–2017)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (122, 'MRU', 'Mauritanian Ouguiya');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (123, 'MTL', 'Maltese Lira');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (124, 'MUR', 'Mauritian Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (125, 'MVR', 'Maldivian Rufiyaa');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (126, 'MWK', 'Malawian Kwacha');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (127, 'MXN', 'Mexican Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (128, 'MXV', 'Mexican Investment Unit');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (129, 'MYR', 'Malaysian Ringgit');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (130, 'MZM', 'Mozambican Metical (1980–2006)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (131, 'MZN', 'Mozambican Metical');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (132, 'NAD', 'Namibian Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (133, 'NGN', 'Nigerian Naira');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (134, 'NIO', 'Nicaraguan Córdoba');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (135, 'NLG', 'Dutch Guilder');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (136, 'NOK', 'Norwegian Krone');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (137, 'NPR', 'Nepalese Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (138, 'NZD', 'New Zealand Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (139, 'OMR', 'Omani Rial');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (140, 'PAB', 'Panamanian Balboa');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (141, 'PEN', 'Peruvian Sol');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (142, 'PGK', 'Papua New Guinean Kina');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (143, 'PHP', 'Philippine Piso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (144, 'PKR', 'Pakistani Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (145, 'PLN', 'Polish Zloty');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (146, 'PTE', 'Portuguese Escudo');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (147, 'PYG', 'Paraguayan Guarani');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (148, 'QAR', 'Qatari Rial');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (149, 'ROL', 'Romanian Leu (1952–2006)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (150, 'RON', 'Romanian Leu');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (151, 'RSD', 'Serbian Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (152, 'RUB', 'Russian Ruble');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (153, 'RUR', 'Russian Ruble (1991–1998)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (154, 'RWF', 'Rwandan Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (155, 'SAR', 'Saudi Riyal');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (156, 'SBD', 'Solomon Islands Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (157, 'SCR', 'Seychellois Rupee');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (158, 'SDD', 'Sudanese Dinar (1992–2007)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (159, 'SDG', 'Sudanese Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (160, 'SEK', 'Swedish Krona');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (161, 'SGD', 'Singapore Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (162, 'SHP', 'St. Helena Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (163, 'SIT', 'Slovenian Tolar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (164, 'SKK', 'Slovak Koruna');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (165, 'SLL', 'Sierra Leonean Leone');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (166, 'SOS', 'Somali Shilling');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (167, 'SRD', 'Surinamese Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (168, 'SRG', 'Surinamese Guilder');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (169, 'SSP', 'South Sudanese Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (170, 'STD', 'São Tomé & Príncipe Dobra (1977–2017)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (171, 'STN', 'São Tomé & Príncipe Dobra');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (172, 'SVC', 'Salvadoran Colón');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (173, 'SYP', 'Syrian Pound');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (174, 'SZL', 'Swazi Lilangeni');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (175, 'THB', 'Thai Baht');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (176, 'TJS', 'Tajikistani Somoni');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (177, 'TMM', 'Turkmenistani Manat (1993–2009)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (178, 'TMT', 'Turkmenistani Manat');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (179, 'TND', 'Tunisian Dinar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (180, 'TOP', 'Tongan Paʻanga');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (181, 'TPE', 'Timorese Escudo');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (182, 'TRL', 'Turkish Lira (1922–2005)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (183, 'TRY', 'Turkish Lira');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (184, 'TTD', 'Trinidad & Tobago Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (185, 'TWD', 'New Taiwan Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (186, 'TZS', 'Tanzanian Shilling');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (187, 'UAH', 'Ukrainian Hryvnia');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (188, 'UGX', 'Ugandan Shilling');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (189, 'USD', 'US Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (190, 'USN', 'US Dollar (Next day)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (191, 'USS', 'US Dollar (Same day)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (192, 'UYI', 'Uruguayan Peso (Indexed Units)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (193, 'UYU', 'Uruguayan Peso');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (194, 'UZS', 'Uzbekistani Som');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (195, 'VEB', 'Venezuelan Bolívar (1871–2008)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (196, 'VEF', 'Venezuelan Bolívar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (197, 'VND', 'Vietnamese Dong');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (198, 'VUV', 'Vanuatu Vatu');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (199, 'WST', 'Samoan Tala');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (200, 'XAF', 'Central African CFA Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (201, 'XAG', 'Silver');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (202, 'XAU', 'Gold');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (203, 'XBA', 'European Composite Unit');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (204, 'XBB', 'European Monetary Unit');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (205, 'XBC', 'European Unit of Account (XBC)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (206, 'XBD', 'European Unit of Account (XBD)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (207, 'XCD', 'East Caribbean Dollar');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (208, 'XDR', 'Special Drawing Rights');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (209, 'XFO', 'French Gold Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (210, 'XFU', 'French UIC-Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (211, 'XOF', 'West African CFA Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (212, 'XPD', 'Palladium');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (213, 'XPF', 'CFP Franc');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (214, 'XPT', 'Platinum');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (215, 'XSU', 'Sucre');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (216, 'XTS', 'Testing Currency Code');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (217, 'XUA', 'ADB Unit of Account');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (218, 'XXX', 'Unknown Currency');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (219, 'YER', 'Yemeni Rial');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (220, 'YUM', 'Yugoslavian New Dinar (1994–2002)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (221, 'ZAR', 'South African Rand');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (222, 'ZMK', 'Zambian Kwacha (1968–2012)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (223, 'ZMW', 'Zambian Kwacha');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (224, 'ZWD', 'Zimbabwean Dollar (1980–2008)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (225, 'ZWL', 'Zimbabwean Dollar (2009)');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (226, 'ZWN', 'ZWN');
INSERT INTO currency (`id`, `iso_code`, `name`) VALUES (227, 'ZWR', 'Zimbabwean Dollar (2008)');
